### ISSUE TITLE
relative() does the opposite of what I'd expect

### ISSUE THREAD

**Issue by Randall-Coding** [iheyunfei/sugar_path#3]
First of all, cool crate and thanks for making it.  

I noticed the relative() function does the opposite of what I intuitively expected it to do.  

If I'm writing `Path::new("/a/b/c/d").relative("/a/b/f/g")`  I would expect this to mean "give me the first path relative to the second path".  That would be `"../../c/d"` but instead it gives me the inverse of that which is `"../../f/g"`.

**Comment by iheyunfei** [comment]
You are right, it was a mistaken design. I will fix it today and release it in 0.0.5. Thanks for using it.

**Comment by Randall-Coding** [comment]
Cool thanks!
