### ISSUE TITLE
perf: reduce allocation frequency in `component_vec_to_path_buf`

### ISSUE THREAD

**Issue by Boshen** [iheyunfei/sugar_path#7]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1430279/211202499-12fc1479-72da-4e18-9c29-96e4d3d94de7.png">

https://github.com/iheyunfei/sugar_path/blob/e86a36b6833d947274def185c80b2360c290b6cb/src/sugar_path.rs#L117-L125

Should probably replace with `map` + `concat` / `join`.

**Comment by iheyunfei** [comment]
Thanks for reminding me.

**Comment by iheyunfei** [comment]
Looks like the source code of std doesn't do pre-allocate memory optimization.

![image](https://user-images.githubusercontent.com/49502170/211208271-62308d83-cb1f-4520-891b-4eb01b93f767.png)

I'm not sure `concat` or  `join` works. Making `Vec<OsStr>` into `PathBuf` is different from making `Vec<&str>` into `String`.

`PathBuf#push` has some special logic in it. It is quite different from `String::push`, which is just a plain `push` on `Vec`

![image](https://user-images.githubusercontent.com/49502170/211208463-fbc18649-ea7c-4960-8bff-ffc526feabb3.png)

**Comment by Boshen** [comment]
Interesting, let's re-open this if I find the perf cost is significant in this case.
